name: Debug demo view development
on:
  workflow_dispatch:
jobs:
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
            version: latest
      - name: Turbo Create
        run: |
          pnpm dlx create-turbo@latest --skip-install --example https://github.com/vercel/turborepo/tree/main/examples/with-svelte 
          tree --gitignore