name: Debug demo view development
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
            version: latest
      - name: Turbo Create
        run: |
          cd demos/playwright-electron/pwe-a-monorepo/
          pnpm install
          pnpm run build
          cd apps
          rm -fr pwe-a/build
          cp -r web/build pwe-a/build
          cd pwe-a
          pnpm exec playwright install --with-deps electron
      - name: Install additional Electron dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libasound2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libxrandr2 \
            libgbm-dev \
            xvfb # For headless GUI support
          # Install libgconf-2-4 from Ubuntu 20.04 repository
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu focal main universe'
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4
      - name: Run tests with Electron
        run: |
          cd demos/playwright-electron/pwe-a-monorepo/apps/pwe-a
          # Start xvfb for headless GUI
          Xvfb :99 -screen 0 1280x720x24 &
          export DISPLAY=:99
          pnpm exec playwright test example.spec.ts