name: Debug demo view development
on:
  workflow_dispatch:
jobs:
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
            version: latest
      - name: Turbo Create
        run: |
          cd demos/playwright-electron/pwe-a-monorepo/
          pnpm install
          pnpm run build
          cd apps
          rm -fr pwe-a/build
          cp -r web/build pwe-a/build
          cd pwe-a
          chmod +x run.sh
          sudo apt install -y imagemagick ### command "import" to take screenshot.
          #### playwright with electron eror about that  https://github.com/electron/electron/issues/47419#issuecomment-2955392579
          # ubuntu latest libgconf-2-4 gone.  response empty if apt search it
          #sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 -y
          apt search libasound2
          sudo apt install libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev -y
          sudo apt install libasound2t64 libasound2-data libasound2-dev libasound2-doc  libasound2-plugins -y
      - name: Playwright Test
        uses: GabrielBB/xvfb-action@v1
        with: 
          run: demos/playwright-electron/pwe-a-monorepo/apps/pwe-a/run.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            # download auto zip
            name: debug
            path: demos/playwright-electron/pwe-a-monorepo/apps/pwe-a/screenshot.png

