name: Debug demo view development
on:
  workflow_dispatch:
jobs:
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
            version: latest
      - name: Turbo Create
        run: |
          cd demos/playwright-electron/pwe-a-monorepo/
          pnpm install
          pnpm run build
          cd apps
          rm -fr pwe-a/build
          cp -r web/build pwe-a/build
          cd pwe-a
          
      - name: Playwright Test
        run: |
          cd demos/playwright-electron/pwe-a-monorepo/
          cd apps
          cd pwe-a
          pwd
          ls node_modules
          rm -fr node_modules
          pnpm install --ignore-workspace
          #https://github.com/electron/electron/issues/20731 The path.txt is missing.
          node node_modules/electron/install.js
          ls -l node_modules
          ls -l ../../node_modules
          npx playwright test --list example.spec.ts
          npx playwright test example.spec.ts