name: Debug demo view development
on:
  workflow_dispatch:
jobs:
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: boot
        run: |
          pnpm init
          pnpm install electron
          node node_modules/electron/install.js
      - name: Playwright Test
        uses: GabrielBB/xvfb-action@v1
        with: 
          run: pnpm exec electron
