name: Windows Tauri Nextjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            demos\\next_tauri_wins\\src-tauri\\target
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Build project
        run: cd demos\\next_tauri_wins && pnpm i && pnpm tauri build -d -v
      - name: Help list build out
        shell: bash
        run: |
          ls demos/next_tauri_wins/src-tauri/target/release
          ls demos/next_tauri_wins/src-tauri/target/debug
      # - name: Upload artifact release
      #   uses: actions/upload-artifact@v2
      #   with:
      #     # download auto zip
      #     name: dist
      #     path: |
      #       demos\\next_tauri_wins\\src-tauri\\target\\release\\next_20240607.exe
      #       demos\\next_tauri_wins\\src-tauri\\target\\release\\nsis
      #       demos\\next_tauri_wins\\src-tauri\\target\\release\\resources
      #       demos\\next_tauri_wins\\src-tauri\\target\\release\\wix
      #       demos\\next_tauri_wins\\src-tauri\\target\\release\\bundle
      - name: Upload artifact debug
        uses: actions/upload-artifact@v2
        with:
            # download auto zip
            name: dist
            path: |
              demos\\next_tauri_wins\\src-tauri\\target\\debug\\next_20240607.exe
              demos\\next_tauri_wins\\src-tauri\\target\\debug\\nsis
              demos\\next_tauri_wins\\src-tauri\\target\\debug\\resources
              demos\\next_tauri_wins\\src-tauri\\target\\debug\\wix
              demos\\next_tauri_wins\\src-tauri\\target\\debug\\bundle
