name: Android capacitor nextjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            demos/next_capacitor_apk/android/.gradle
            demos/next_capacitor_apk/android/app/build
          key: ${{ runner.os }}-pnpm-gradle-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-gradle-
      - name: Build project
        run: |
          cd demos/next_capacitor_apk && pnpm i && pnpm run build && npx cap sync
          cd android && ./gradlew --no-daemon assembleDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            # download auto zip
            name: debug
            path: demos/next_capacitor_apk/android/app/build/outputs/apk/debug
