name: Windows Rocksdb-rs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v4
        name: Setup rocksdb build cache
        with:
          path: 
            demos\\rocksdb-rs\\migrate_te\\target
          key: ${{ runner.os }}-rocksdb-rs }}
          restore-keys: |
            ${{ runner.os }}-rocksdb-rs
      - name: Build project
        run: cd demos\\rocksdb-rs\\migrate_te && cargo build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            # download auto zip
            name: dist
            path: demos\\rocksdb-rs\\migrate_te\\target\\release\\abcd.exe
